version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:


    build: .
    image: aarav08/docker-node
    ports:
      - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.4.18
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=aarav
      - MONGO_INITDB_ROOT_PASSWORD=mydatabase
    volumes:
      - mongo-vol:/data/db
  
  redis:
    image: redis

volumes:
 mongo-vol:
