version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo-db:
    image: mongo:4.4.18
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=aarav
      - MONGO_INITDB_ROOT_PASSWORD=mydatabase
    volumes:
      - mongo-vol:/data/db

volumes:
 mongo-vol:
